package org.example;

import java.util.List;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;


public class Main {
    public static void main(String[] args) {
        String code = "a: int128;";

        BytecodeGenerator bytecodeGenerator = new BytecodeGenerator();
        List<Byte> bytecode = bytecodeGenerator.generateBytecode(code);

        System.out.println("Generated Bytecode:");
        for (byte b : bytecode) {
            System.out.printf("%02X ", b);
        }
        System.out.println();
    }
}